########## Startup Notification ##########
- alias: Notify when Homeassistant starts
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: notify.telegram
      data:
        title: "ich bin lebendig :)"
        message: "Das Leben ist so wunderschön."

########## Shutdown Notification ##########
- alias: Notify when Homeassistant stops
  trigger:
    platform: homeassistant
    event: shutdown
  action:
    - service: notify.telegram
      data:
        title: "Ich bin tot :("
        message: "Ich komme als Geist wieder und verhexe deinen Penis."

########## Only Play Music if Motion was detected and Media Player is off or paused ##########
########## Don´t start Music everytime new if someone didnot move for a few seconds ##########
- alias: Send Telegram and play Music in kitchen
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_sensor_motion
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '07:30:00'
        before: '01:00:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
          - sun
      - condition: or
        conditions:
          - condition: state
            entity_id: media_player.badezimmer
            state: "paused"
          - condition: state
            entity_id: media_player.badezimmer
            state: "idle"
          - condition: state
            entity_id: media_player.badezimmer
            state: "off"
  action:
#    - service: notify.telegram
#      data:
#        title: Bewegung erkannt
#        message: "Wer war das?"
    - service: media_player.play_media
      data_template:
        entity_id: media_player.badezimmer
        media_content_type: audio/mp3
        media_content_id: "http://stream12.iloveradio.de/iloveradio6-aac.mp3"
<<<<<<< HEAD
=======
        
>>>>>>> 6a05ef71d191e787bfaacd4983c5d53e4d227c63


########## Stop Music after Motion was not detected for 30 Seconds ##########
- alias: Stop after no motion
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_sensor_motion
    to: 'off'
    for:
      seconds: 15
<<<<<<< HEAD
  condition:
=======
  condition: 
>>>>>>> 6a05ef71d191e787bfaacd4983c5d53e4d227c63
    condition: or
    conditions:
      - condition: state
        entity_id: media_player.badezimmer
        state: "playing"
  action:
    - service: media_player.media_pause
      data:
        entity_id: media_player.badezimmer
<<<<<<< HEAD
=======
    
>>>>>>> 6a05ef71d191e787bfaacd4983c5d53e4d227c63
